
spring:
  # --- Datasource Configuration ---
  datasource:

    # MySQL
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/${DB_NAME}
     username: ${DB_USER}
     password: ${DB_PWD}


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

  # --- Paging Configuration ---
  data:
    web:
      pageable:
        default-page-size: 10 # 기본 페이지 사이즈
        max-page-size: 1000 # 최대 페이지 사이즈

    redis:
      host: localhost
      port: 6379

  liquibase:
    change-log: classpath:/db/db.changelog-master.yaml
    enabled: true
    contexts: local

jwt:
  secret: ${JWT_SECRET}
